.PHONY: clean All

All:
	@echo "----------Building project:[ mandelbrot - so-utf8-x64-release ]----------"
	@"$(MAKE)" -f  "mandelbrot.mk" PrePreBuild && "$(MAKE)" -f  "mandelbrot.mk"
clean:
	@echo "----------Cleaning project:[ mandelbrot - so-utf8-x64-release ]----------"
	@"$(MAKE)" -f  "mandelbrot.mk" clean
